---
- hosts: win
  tasks:
    - name: Ensure SNMP is started
      win_service:
        name: snmptrap
        state: started

    - name: Installing IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes

    - name: Copy webpage
      win_copy:
        src: index.html
        dest: 'C:\inetpub\wwwroot\index.html'
      notify:
